[package]
name = "rustpass"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.46", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.27"
rusqlite = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }
